### ISSUE TITLE
SSL error when connecting to github

### ISSUE THREAD

**Issue by juanibiapina** [edgarjs/alfred-github-repos#13]
This started happening rather recently:

```
[ERROR: action.script] /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:921:in `connect': SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: tlsv1 alert protocol version (OpenSSL::SSL::SSLError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:921:in `block in connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:921:in `connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:851:in `start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:582:in `start'
	from github:152:in `get'
	from github:44:in `test_authentication'
...
```

I'm trying to investigate but I thought you might have some thoughts.

**Comment by juanibiapina** [comment]
This is caused by the ruby version of osx not having TLS 1.2 support. LS 1 and 1.1 support was dropped from github on February.

https://githubengineering.com/crypto-removal-notice/

**Comment by jessicalevine** [comment]
If you're using RVM, a quick fix for this is adding:

```
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

```

to the top of all your script and the `gh` input

**Comment by juanibiapina** [comment]
Any specific reason for closing ?

**Comment by edgarjs** [comment]
A new version of the workflow has been released. Please test it and let me know if the error persists.
