### ISSUE TITLE
Setting host generates an error

### ISSUE THREAD

**Issue by mguterl** [edgarjs/alfred-github-repos#14]
```
bin/github-repos host https://whatever.com
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/json/common.rb:224:in `generate': only generation of JSON objects or arrays allowed (JSON::GeneratorError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/json/common.rb:224:in `generate'
	from /Users/guterlm/Downloads/github-repos/lib/local_storage.rb:40:in `serialize'
	from /Users/guterlm/Downloads/github-repos/lib/local_storage.rb:16:in `block in put'
	from /Users/guterlm/Downloads/github-repos/lib/local_storage.rb:15:in `open'
	from /Users/guterlm/Downloads/github-repos/lib/local_storage.rb:15:in `put'
	from /Users/guterlm/Downloads/github-repos/lib/github/api.rb:22:in `configure_host'
	from bin/github-repos:33:in `configure_host'
	from bin/github-repos:84:in `<main>'
```

https://github.com/edgarjs/alfred-github-repos/blob/master/lib/github/api.rb#L22-L29 is trying to encode/decode a single string value instead of an object or array.

**Comment by edgarjs** [comment]
I tested it and it's working. It seems that the Ruby version you're using may be different, I'm using Ruby 2.6.

**Comment by mguterl** [comment]
I guess I would expect this to work with the default version of Ruby provided by Mac OS. I could send a PR your way if you're interested?

**Comment by edgarjs** [comment]
You're right, maybe a more portable implementation could work. Yes of course, you can send a PR.
