### ISSUE TITLE
gh command is hanging

### ISSUE THREAD

**Issue by Morriz** [edgarjs/alfred-github-repos#29]
Hi, I have seen the plugin work in OSX Big Sur, but since a couple of days I see no more gh output (the token is working tho):

```
[15:04:07.575] Github Repos[Script Filter] Queuing argument 'h'
[15:04:07.753] Github Repos[Script Filter] Queuing argument 'he'
[15:04:07.834] Github Repos[Script Filter] Queuing argument 'hel'
[15:04:09.049] Github Repos[Script Filter] Queuing argument 'help'
[15:04:23.467] Github Repos[Script Filter] Script with argv 'h' finished
[15:04:23.473] ERROR: Github Repos[Script Filter] Code 1: /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:949:in `rescue in block in connect': Failed to open TCP connection to api.github.com:443 (Bad file descriptor - connect(2) for "api.github.com" port 443) (Errno::EBADF)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:946:in `block in connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:103:in `timeout'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:945:in `connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:930:in `do_start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:919:in `start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:605:in `start'
	from /Users/Morriz/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.331E0927-D269-483A-B327-5C69C738D632/lib/github/api.rb:94:in `get'
	from /Users/Morriz/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.331E0927-D269-483A-B327-5C69C738D632/lib/github/api.rb:55:in `reset_cache'
	from /Users/Morriz/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.331E0927-D269-483A-B327-5C69C738D632/lib/github/api.rb:40:in `search_repos'
	from bin/github-repos:72:in `search'
	from bin/github-repos:109:in `<main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:947:in `initialize': Bad file descriptor - connect(2) for "api.github.com" port 443 (Errno::EBADF)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:947:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:947:in `block in connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:103:in `timeout'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:945:in `connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:930:in `do_start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:919:in `start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:605:in `start'
	from /Users/Morriz/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.331E0927-D269-483A-B327-5C69C738D632/lib/github/api.rb:94:in `get'
	from /Users/Morriz/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.331E0927-D269-483A-B327-5C69C738D632/lib/github/api.rb:55:in `reset_cache'
	from /Users/Morriz/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.331E0927-D269-483A-B327-5C69C738D632/lib/github/api.rb:40:in `search_repos'
	from bin/github-repos:72:in `search'
	from bin/github-repos:109:in `<main>'
[15:04:23.686] Github Repos[Script Filter] Script with argv 'help' finished
[15:04:23.699] ERROR: Github Repos[Script Filter] Code 1: /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:949:in `rescue in block in connect': Failed to open TCP connection to api.github.com:443 (Bad file descriptor - connect(2) for "api.github.com" port 443) (Errno::EBADF)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:946:in `block in connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:103:in `timeout'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:945:in `connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:930:in `do_start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:919:in `start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:605:in `start'
	from /Users/Morriz/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.331E0927-D269-483A-B327-5C69C738D632/lib/github/api.rb:94:in `get'
	from /Users/Morriz/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.331E0927-D269-483A-B327-5C69C738D632/lib/github/api.rb:55:in `reset_cache'
	from /Users/Morriz/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.331E0927-D269-483A-B327-5C69C738D632/lib/github/api.rb:40:in `search_repos'
	from bin/github-repos:72:in `search'
	from bin/github-repos:109:in `<main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:947:in `initialize': Bad file descriptor - connect(2) for "api.github.com" port 443 (Errno::EBADF)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:947:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:947:in `block in connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:103:in `timeout'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:945:in `connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:930:in `do_start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:919:in `start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:605:in `start'
	from /Users/Morriz/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.331E0927-D269-483A-B327-5C69C738D632/lib/github/api.rb:94:in `get'
	from /Users/Morriz/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.331E0927-D269-483A-B327-5C69C738D632/lib/github/api.rb:55:in `reset_cache'
	from /Users/Morriz/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.331E0927-D269-483A-B327-5C69C738D632/lib/github/api.rb:40:in `search_repos'
	from bin/github-repos:72:in `search'
	from bin/github-repos:109:in `<main>'
```

Any ideas?

**Comment by edgarjs** [comment]
Hi. Thanks for reporting. This sounds like a network issue (proxy, firewall, etc.). Can you test in a different network and/or computer to confirm?

**Comment by Morriz** [comment]
Yeah, it was little snitch that I adapted the rule for (to not check identity, which is a shame as I think Alfred should carry a valid identity, but maybe it can't guarantee identity for the plugins and that is the real problem).

Anyway, now I get this:
```
[21:44:50.442] ERROR: Github Repos[Script Filter] Code 1: /Users/Morriz/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.331E0927-D269-483A-B327-5C69C738D632/lib/github/repo.rb:37:in `from_api_response': no implicit conversion of Symbol into Integer (TypeError)
	from /Users/Morriz/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.331E0927-D269-483A-B327-5C69C738D632/lib/github/api.rb:57:in `block in reset_cache'
	from /Users/Morriz/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.331E0927-D269-483A-B327-5C69C738D632/lib/github/api.rb:56:in `each'
	from /Users/Morriz/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.331E0927-D269-483A-B327-5C69C738D632/lib/github/api.rb:56:in `map'
	from /Users/Morriz/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.331E0927-D269-483A-B327-5C69C738D632/lib/github/api.rb:56:in `reset_cache'
	from /Users/Morriz/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.331E0927-D269-483A-B327-5C69C738D632/lib/github/api.rb:40:in `search_repos'
	from bin/github-repos:72:in `search'
	from bin/github-repos:109:in `<main>'
```

**Comment by edgarjs** [comment]
Can you try deleting the local cache manually and then try again? The cache
folder is under `~/.config/github-repos/cache`.

**Comment by Morriz** [comment]
Same error unfortunately. Also reloaded alfred cache.

**Comment by edgarjs** [comment]
I've been working on a new version for the workflow. But it's still not very well tested. If you're ok with trying that one, let me know if that works. I'm attaching the bundle or you can build it from source at bee41ecb9443436e43bdc98a9d5f57ce06e7031d.

[gh-repos-3.0.0.alfredworkflow.zip](https://github.com/edgarjs/alfred-github-repos/files/5646552/gh-repos-3.0.0.alfredworkflow.zip)

**Comment by Morriz** [comment]
Thanks a lot! I will try asap

**Comment by Morriz** [comment]
Love it already! So nice to have more options ;)

**Comment by edgarjs** [comment]
Thanks, I'll close this issue for now but feel free to open more if you have another issue.
